### ISSUE TITLE
[1.18.2] Singleplayer Crash after world is loaded

### ISSUE THREAD

**Issue by DeshiDesu** [dfdyz/EpicAddon#12]
epicaddon-18.0.6.53.jar

[crash-2023-04-03_21.58.37-server.txt](https://github.com/dfdyz/EpicAddon/files/11143934/crash-2023-04-03_21.58.37-server.txt)

**Comment by dfdyz** [comment]
I had fixed it, but I forgot to upload file, sorry.
And you need to update efm to 18.3.8(which fixed crash by mob holding void on off hand).

**Comment by DeshiDesu** [comment]
Thank you for letting me know! I didn't know that version of efm existed 😅

**Comment by DeshiDesu** [comment]
[crash-2023-04-10_15.10.40-server.txt](https://github.com/dfdyz/EpicAddon/files/11193367/crash-2023-04-10_15.10.40-server.txt)
[crash-2023-04-10_15.22.36-client.txt](https://github.com/dfdyz/EpicAddon/files/11193370/crash-2023-04-10_15.22.36-client.txt)

This crash happened while spawning zombies

**Comment by dfdyz** [comment]
[epicaddon-18.0.6.541.zip](https://github.com/dfdyz/EpicAddon/files/11200261/epicaddon-18.0.6.541.zip)

**Comment by dfdyz** [comment]
Try this. if its fixed i will release it

**Comment by DeshiDesu** [comment]
I tried the above file and it worked perfectly without experiencing any crashes.

**Comment by DeshiDesu** [comment]
However, there is something I want to point out, zombies that spawn holding the Elucidator sword does not have aggression:
![2023-04-11_20 09 37](https://user-images.githubusercontent.com/120287925/231315201-c63308f3-dac0-4beb-a96c-b3c1acd6bbb0.png)
This is the only weapon of this mod that are spawned alongside zombies. Is it possible to disable this?

**Comment by dfdyz** [comment]
Yes, the mob has not ai while it holding this mods' weapon. because efm need to coding 
an ai rule for every type of weapon. and i didn't do this.
don't worry, this is what i plan to do.
