### ISSUE TITLE
Genshin Bow Attributes does not apply

### ISSUE THREAD

**Issue by qVoidreaver** [dfdyz/EpicAddon#13]
I'm using latest recently released version and I'm trying to leave default bow and mods like "Genshin Bow". The "Genshin Bow" weapon type applies, but the damage stats, etc., do not.

**Comment by dfdyz** [comment]
I need more detial.
damage is multiplied a rate while calculation(basic attack is 33%)
attack speed is locked by code
impact has bi effect

**Comment by qVoidreaver** [comment]
I created a datapack as a test and put extrapolated damage for test (50 damage), and no matter what I put, the damage remains at 0.23 (normal attack) and 1 (charged attack)

**Comment by qVoidreaver** [comment]
This time it applied. I don't know if it was this new update, but maybe I was doing something wrong.
