### ISSUE TITLE
作者大大求求了，希望能开发一个原神的下落攻击的动作或者说攻击模式

### ISSUE THREAD

**Issue by Dawn2329** [dfdyz/EpicAddon#8]
作者大大，真的很喜欢你做的这个模组
这个血条样式也是真的很喜欢
作为一名宵宫厨，看到这个宵宫攻击动作，真的太谢谢您了，能让我在MC中感受原神的攻击方式
希望作者大大能在多做点原神里的动作
强烈建议开发一个  原神的下落攻击 的攻击方式

**Comment by dfdyz** [comment]
等暑假吧，现在忙
