### ISSUE TITLE
mod crashes on server

### ISSUE THREAD

**Issue by UnKZero** [dfdyz/EpicAddon#9]
[crash-2023-03-06_14.20.10-fml.txt](https://github.com/dfdyz/EpicAddon/files/10899389/crash-2023-03-06_14.20.10-fml.txt)

**Comment by dfdyz** [comment]
EpicfightPirates and EFM-ACG-Addon are incompatible.
But it really has crash bug on server. I will fix it on next update later.

**Comment by UnKZero** [comment]
alr ty
